# ==================================================
#  MangoWC - (2026)
#  Kitty Configuration for Mango + Noctalia
# ==================================================

linux_display_server wayland
font_family Fira Code Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto
font_size 11.0
disable_ligatures never
cursor_shape beam
scrollback_lines 10000
repaint_delay 6
sync_to_monitor yes
confirm_os_window_close 0

# Window
window_padding_width 6
background_opacity 0.90

# Noctalia Dark Palette
foreground            #f3edf7
background            #070722
selection_foreground  #0e0e43
selection_background  #9BFECE

# Color palette
# Black
color0   #11112d
color8   #7c80b4

# Red
color1   #FD4663
color9   #ffb4ab

# Green
color2   #9BFECE
color10  #bdfeda

# Yellow
color3   #fff59b
color11  #fff9c4

# Blue
color4   #a9aefe
color12  #c5c9fe

# Magenta
color5   #ffafd7
color13  #ffcde6

# Cyan
color6   #8fd6a8
color14  #d8ffe6

# White
color7   #d3e0d8
color15  #f8fffa

# Cursor
cursor #9BFECE
cursor_text_color #070722

# Tab bar
tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted
tab_bar_align left
tab_bar_min_tabs 2
active_tab_font_style bold
active_tab_foreground #0e0e43
active_tab_background #9BFECE
inactive_tab_foreground #7c80b4
inactive_tab_background #11112d

# Keybindings
map ctrl+left resize_window narrower
map ctrl+right resize_window wider
map ctrl+up resize_window taller
map ctrl+down resize_window shorter
map ctrl+home resize_window reset

# Splits layout
enabled_layouts splits,stack
map ctrl+shift+enter launch --location=vsplit --cwd=current
