# ==================================================
#  MangoWC - (2026)
#  Mango Monitor Rules
# ==================================================

# Default monitor rule (matches any output, 0 = preferred native resolution and refresh rate)
# Format: monitorrule=name:<pattern>,width:<w>,height:<h>,refresh:<hz>,x:<x>,y:<y>,scale:<s>,vrr:<0|1>
monitorrule=name:.*,width:0,height:0,refresh:0,x:0,y:0,scale:1.0,vrr:0
