# ==================================================
#  MangoWC - (2026)
#  Mango Monitor Rules
# ==================================================

# Default monitor rule (matches any output, auto-detects native resolution and refresh rate)
# Format: monitorrule=name:<pattern>,width:<w>,height:<h>,refresh:<hz>,x:<x>,y:<y>,scale:<s>,vrr:<0|1>
monitorrule=name:.*,scale:1.0,vrr:0
