# ==================================================
#  MamgoDOTS - (2026)
#  Mango Window Rules
# ==================================================

# Floating kitty window (spawned via SUPER+CTRL+Return)
windowrule=isfloating:1,width:900,height:600,title:floating-kitty

# Picture-in-picture
windowrule=isfloating:1,title:Picture-in-Picture
